export const API_URLS = {
  auth: {
    login: "/auth/login",
  },
  admin: {
    menu: "/admin/menu_items",
    users: "/admin/users",
  },
  accounts: {
    byId: (accountId) => `/accounts/${accountId}`,
    list: "/accounts",
    update: (accountId) => `/accounts/${accountId}`,
  },
  categories: {
    list: "/categories",
    update: (categoryId) => `/categories/${categoryId}`,
  },
  blogs: {
    byId: (blogId) => `/admin/blogs/${blogId}`,
    list: "/admin/blogs",
    update: (blogId) => `/admin/blogs/update/${blogId}`,
  },
  dashboard: {
    overview: "/admin/dashboard",
    currentMonthTripSales: "/admin/current-month-trip-sales-report",
    packageProfitMargin: "/admin/package-profit-margin",
  },
  onlinePaymentConfig: {
    byId: (configurationId) => `/admin/online-configure/${configurationId}`,
    list: "/admin/online-configure",
    update: "/admin/online-configure/update",
  },
  recurringExpenses: {
    create: "/recurring-expenses",
    list: "/recurring-expenses",
    run: (recurringExpenseId) => `/recurring-expenses/${recurringExpenseId}/run`,
    runDue: "/recurring-expenses/run-due",
    update: (recurringExpenseId) => `/recurring-expenses/${recurringExpenseId}`,
  },
  hotels: {
    byId: (hotelId) => `/hotel/${hotelId}`,
    list: "/admin/hotel",
    update: (hotelId) => `/admin/hotel/update/${hotelId}`,
  },
  menuItems: {
    byId: (menuItemId) => `/admin/menu_items/${menuItemId}`,
    list: "/admin/menu_items",
    update: (menuItemId) => `/admin/menu_items/update/${menuItemId}`,
  },
  reports: {
    accountBalances: "/reports/account-balances",
    accountBalance: "/admin/accountBalance",
    accountBalanceHistory: (type) => `/admin/accountHistory/${encodeURIComponent(type)}`,
    accountHistorySearch: "/admin/account-history",
    categoryBreakdown: "/reports/category-breakdown",
    daywiseExpenses: "/reports/daywise-expenses",
    weeklyCurrentMonthAnalysis: "/reports/weekly-current-month-analysis",
    customerValue: "/admin/customerValue",
    dailyBalance: "/admin/monthlyDailyBalanceReport",
    dailyBalanceHistory: "/admin/monthly-daily-balance-reports",
    financialReport: "/admin/financial_report",
    highCancellationPackages: "/admin/high-cancellation-packages",
    lowOccupancyTripReport: "/admin/low-occupancy-trip-report",
    lowPerformingPackages: "/admin/low-performing-packages",
    monitoring: "/admin/monitoring",
    monthRunningBalance: "/admin/monthRunningBalance",
    overallSales: "/admin/overall-sales-summary",
    routeWiseSales: "/admin/route-wise-sales-summary",
    summary: "/reports/summary",
    ticketStatusReport: "/admin/ticket-status-report",
    tripPerformance: "/admin/tripPerformance",
    vehicleTracking: "/admin/useageOfVehicle",
    vehicleWiseSeatDetails: (vehicleId) => `/admin/vehiclewiseseat/${vehicleId}`,
    vehicleWiseSeatTotal: "/admin/vehiclewisetotalseat",
  },
  tickets: {
    list: "/admin/tickets",
    update: (ticketId) => `/admin/tickets/update/${ticketId}`,
  },
  refunds: {
    list: "/admin/refund",
    disburse: "/admin/refund/disburse",
  },
  transfers: {
    create: "/transfers",
    list: "/transfers",
    update: (transferId) => `/transfers/${transferId}`,
    withdrawToCash: "/transfers/withdraw-to-cash",
  },
  transactions: {
    deposit: "/transactions/deposit",
    expense: "/transactions/expense",
    income: "/transactions/income",
    list: "/transactions",
    update: (transactionId) => `/transactions/${transactionId}`,
  },
  visaApplications: {
    assign: "/admin/visa/assign",
    byId: (applicationId) => `/admin/visa/applications/${applicationId}`,
    documentVerify: "/admin/visa/document-verify",
    list: "/admin/visa/applications",
    print: (applicationId) => `/admin/visa/print/${applicationId}`,
    statusUpdate: "/admin/visa/status-update",
    update: (applicationId) => `/admin/visa/applications/update/${applicationId}`,
  },
  resources: {
    guideDropdown: "/admin/guide/dropdown",
    packageCreate: "/admin/packages/create",
    packageDetails: (packageId) => `/packages/${packageId}`,
    packages: "/admin/packages",
    routes: "/admin/routes",
    routeDropdown: "/admin/routes/dropdown",
    visaCountries: "/admin/visa/countries",
    visaCountriesDropdown: "/admin/visa/countries/dropdown",
    visaCountriesUpdate: (countryId) => `/admin/visa/countries/update/${countryId}`,
    visaCountryById: (countryId) => `/admin/visa/countries/${countryId}`,
    visaTypes: "/admin/visa/types",
    visaTypesUpdate: (visaTypeId) => `/admin/visa/types/update/${visaTypeId}`,
    visaTypeById: (visaTypeId) => `/admin/visa/types/${visaTypeId}`,
    vehicles: "/admin/vehicles",
    vehicleDropdown: "/admin/vehicles/dropdown",
    seats: "/admin/seat",
    trips: "/admin/trip",
    tripDropdown: "/admin/trip/dropdown",
    tripSingle: "/admin/single/trip",
    tripSummary: "/admin/tripsummery",
    tripUpdate: (tripId) => `/admin/trip/update/${tripId}`,
  },
};
